### DISCUSSION TITLE
Enable passing the `access_token_scopes` configuration to `google-github-actions/auth` on tfaction-root

### DISCUSSION THREAD

**Discussion by rrreeeyyy** [suzuki-shunsuke/tfaction#1325] [Deprecated (Feature Request)] [answered]
### Feature Overview

We would like to enable passing the `access_token_scopes` configuration item to `google-github-actions/auth`.

`access_token_scopes` is a configuration value that specifies the OAuth 2.0 access scopes for the access token generated by Workload Identity Federation. By making this configurable from tfaction, it becomes possible to handle scopes other than `https://www.googleapis.com/auth/cloud-platform` in a terraform environment using tfaction.

### Why is the feature needed?

In our terraform environment using tfaction, we manage not only GCP but also Google Workspace through terraform. To operate elements such as Google Workspace's groups, it's necessary to add various scopes beyond the default `https://www.googleapis.com/auth/cloud-platform`, and these need to be passed to `google-github-actions/auth`.

For instance, in the actual environment we use, we pass the following as `access_token_scopes` to `google-github-actions/auth`:

```
access_token_scopes: 'https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/userinfo.email, https://www.googleapis.com/auth/apps.groups.settings, https://www.googleapis.com/auth/admin.directory.group'
```

Currently, instead of using `gcp_service_account` or `gcp_workload_identity_provider` from tfaction-root, we add and use code to call `google-github-actions/auth` directly in `test.yml` and `apply.yml`. 

We want to make this configurable in tfaction-root to simplify the tfaction workflow.

### Does the feature include Breaking Changes?

No. I believe that this change will likely not be a breaking change.

### Example Code

GitHub Actions

- We will use the `apply.yml` and `test.yml` templates as they are.

tfaction-root.yaml

```yaml
- working_directory: google_workspace/
  target: google_workspace/
  terraform_plan_config:
    gcp_service_account: terraform-plan@example.iam.gserviceaccount.com
    gcp_workload_identity_provider: projects/000000000000/locations/global/workloadIdentityPools/github/providers/tfaction
    gcp_access_token_scopes: 'https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/userinfo.email, https://www.googleapis.com/auth/apps.groups.settings, https://www.googleapis.com/auth/admin.directory.group' 
```

tfaction.yaml

```yaml
{} # or can override configuration of `gcp_access_token_scopes` in here
```

### Reference

* https://github.com/google-github-actions/auth

**Comment by rrreeeyyy** [comment]
To pass `access_token_scopes` in this way, it was necessary to set `'access_token'` in `token_format`. Therefore, to meet the requirements, it seems necessary to make `gcp_token_format` also configurable in tfaction-root.

Consequently, the ideal configuration for tfaction-root would be as follows:

```
- working_directory: google_workspace/
  target: google_workspace/
  terraform_plan_config:
    gcp_service_account: terraform-plan@example.iam.gserviceaccount.com
    gcp_workload_identity_provider: projects/000000000000/locations/global/workloadIdentityPools/github/providers/tfaction
    gcp_token_format: access_token
    gcp_access_token_scopes: 'https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/userinfo.email, https://www.googleapis.com/auth/apps.groups.settings, https://www.googleapis.com/auth/admin.directory.group' 
```
