### DISCUSSION TITLE
trivy usage

### DISCUSSION THREAD

**Discussion by GurayCetin** [suzuki-shunsuke/tfaction#1537] [Deprecated (Question and Answer)] [answered]
### Question

I could not figure out to use trivy with tfaction. 
It's enabled in tfaction-root.yaml. added to aqua import as trivy.yaml. 

Is there any way to specify config path for trivy.yaml? it's expecting it in running terraform folder.

Other one is when i changed timeout to 10m, it's giving me the outputs but not seeing them as comment. i have enabled reviewdog and added yaml to aqua imports. 

### Example Code

GitHub Actions

```yaml

```

tfaction-root.yaml

```yaml

```

tfaction.yaml

```yaml

```

**Comment by suzuki-shunsuke** [comment]
I'd really appreciate it if you separate discussions per question from the next time.

~~As of~~ From tfaction v1, trivy is run by the test action by default.

https://github.com/suzuki-shunsuke/tfaction/blob/15be319018867260fa743078cd453ba8acbcf638/test/action.yaml#L29-L34

Trivy is run on each working directory, so please add the file `trivy.yaml` on each working directory.

https://aquasecurity.github.io/trivy/v0.49/docs/configuration/

> Is there any way to specify config path for trivy.yaml?

According to the document of Trivy, I think you can specify the path by the environment variable `TRIVY_CONFIG`.

https://aquasecurity.github.io/trivy/v0.49/docs/configuration/#environment-variables

**Reply by GurayCetin** [reply]
it would be good to use one file for each folder. so no need to use same config file for each folder. 
I am not sure how to specify TRIVY_CONFIG in which file?

**Reply by suzuki-shunsuke** [reply]
> I am not sure how to specify TRIVY_CONFIG in which file?

You can set the environment variable in the GitHub Actions workflow.

e.g.

```yaml
      - uses: suzuki-shunsuke/tfaction/test@v1.1.0
        with:
          github_token: ${{steps.generate_token.outputs.token}}
          secrets: ${{steps.setup.outputs.secrets}}
        env:
          TRIVY_CONFIG: ${{ github.workspace }}/trivy.yaml
```
