### ISSUE TITLE
Change configuration structure

### ISSUE THREAD

**Issue by suzuki-shunsuke** [suzuki-shunsuke/tfaction#108]
```yaml
target_groups:
- working_directory:
  target:
  jobs:
  - job_id: terraform-plan # GITHUB_JOB
    aws_assume_role_arn:
    secrets:
    # ...
```

**Comment by suzuki-shunsuke** [comment]
#111

**Comment by suzuki-shunsuke** [comment]
AS IS

```yaml
secrets:
  FOO: BAR
```

TO BE

```yaml
secrets:
- env_name: FOO
  secret_name: BAR
```
