### ISSUE TITLE
Cache Terraform plugins and modules

### ISSUE THREAD

**Issue by suzuki-shunsuke** [suzuki-shunsuke/tfaction#1487]
### Feature Overview

Cache Terraform plugins and modules

### Why is the feature needed?

To speed up CI.

**Comment by rochana-atapattu** [comment]
I am using github/cache action to achieve this (I have not had time to thoroughly asses the impact).
```yaml
- uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
   with:
      save-always: true
      path: ~/.local/share/aquaproj-aqua
      key: test-modules-v1-aqua-installer-${{runner.os}}-${{runner.arch}}-${{hashFiles('**/aqua/**/*.yaml')}} # Change key
      restore-keys: |
          test-modules-v1-aqua-installer-${{runner.os}}-${{runner.arch}}-
```
and
```yaml
- name: Cache Terraform
   uses: actions/cache@ab5e6d0c87105b4c9c2047343972218f562e4319 # v4
     with:
       path: |
         ${{ steps.target-config.outputs.working_directory }}/.terraform/
       key: ${{ steps.working_directory_name.outputs.working_directory }}-${{ runner.os }}-terraform-${{ hashFiles('${{ steps.target-config.outputs.working_directory }}/.terraform.lock.hcl') }}
       restore-keys: |
         ${{ steps.working_directory_name.outputs.working_directory }}-${{ runner.os }}-terraform-
```
