### ISSUE TITLE
Support OpenTofu

### ISSUE THREAD

**Issue by suzuki-shunsuke** [suzuki-shunsuke/tfaction#1551]
### Feature Overview

Support using OpenTofu instead of Terraform.

https://opentofu.org/

### Why is the feature needed?

OpenTofu is a fork of Terraform that is open-source, community-driven, and managed by the Linux Foundation.

Some people use OpenTofu instead of Terraform.
It's great if tfaction supports OpenTofu too.

### Example Code

GitHub Actions

```yaml

```

tfaction-root.yaml

```yaml
opentofu:
  enabled: true

target_groups:
- working_directory: aws/
```

tfaction.yaml

```yaml

```
