### ISSUE TITLE
modules README.md is always overwritten

### ISSUE THREAD

**Issue by rochana-atapattu** [suzuki-shunsuke/tfaction#1582]
### tfaction version

1.2.1

### Overview

when generating the terraform docs in module test READMe.md is always overwritten

### How to reproduce

tfaction-root.yaml

```yaml
---
plan_workflow_name: pull_request_target # Mandatory
label_prefixes:
  tfmigrate: "migrate:"
# skip_create_pr: true

# drift_detection:
#   # issue_repo_owner:
#   # issue_repo_name:
#   minimum_detection_interval: 5 # 5 days. By default 7 days.
#   num_of_issues: 3 # 3 working directories are checked per workflow run. By default 1 working directory is checked.

tflint:
  enabled: true
tfsec:
  enabled: false
trivy:
  enabled: true

# scaffold_working_directory:
#   skip_adding_aqua_packages: true

aqua:
  update_checksum:
    # Update aqua-checksums.json in `setup` action
    enabled: true # default is false
    skip_push: false # default is false
    prune: true # default is false

target_groups:
  - working_directory: configurations/state-buckets-state
    target: configurations/state-buckets-state
    gcs_bucket_name_tfmigrate_history: '<S3 Bucket Name for tfmigrate history files>' # CHANGEME
    template_dir: templates/gcp

  - working_directory: gcp/
    target: gcp/
    gcs_bucket_name_tfmigrate_history: '<GCS Bucket Name for tfmigrate history files>'
    template_dir: templates/gcp
    # terraform_plan_config:
    #   gcp_service_account: terraform-plan@example.iam.gserviceaccount.com
    #   gcp_workload_identity_provider: projects/000000000000/locations/global/workloadIdentityPools/github/providers/tfaction
    # tfmigrate_plan_config:
    #   gcp_service_account: terraform-plan@example.iam.gserviceaccount.com
    #   gcp_workload_identity_provider: projects/000000000000/locations/global/workloadIdentityPools/github/providers/tfaction
    # terraform_apply_config:
    #   gcp_service_account: terraform-apply@example.iam.gserviceaccount.com
    #   gcp_workload_identity_provider: projects/000000000000/locations/global/workloadIdentityPools/github/providers/tfaction
    # tfmigrate_apply_config:
    #   gcp_service_account: terraform-apply@example.iam.gserviceaccount.com
    #   gcp_workload_identit
```

tfaction.yaml

```yaml

```

GitHub Actions Workflow

```yaml

```

Other related code such as local Registry

```

```

GitHub Actions' log

```

Run ! test -f .terraform.lock.hcl || rm .terraform.lock.hcl
Run set -euo pipefail
time="2024-03-13T08:25:35Z" level=info msg="download and unarchive the package" aqua_version=2.24.0 env=linux/amd64 exe_name=terraform-docs package_name=terraform-docs/terraform-docs package_version=v0.16.0 program=aqua registry=standard
Error: Please generate Module's README.md with terraform-docs.
Error: Process completed with exit code 1.
```

### Expected behaviour

inject terraform docs to README.md without overwriting the content

### Actual behaviour

overwrites entire README.md

### Note

we can do the following to inject docs anywhere in the README.md the user wants. this will give the user a choice where to add docs.
.terraform-docs.yml
```yaml
formatter: markdown
header-from: docs/header.md
footer-from: docs/footer.md
output:
  file: README.md
  mode: inject
```
README.md
```md
<!-- BEGIN_TF_DOCS -->
    {{ .Content }}
<!-- END_TF_DOCS -->
## Requirements

Before this module can be used on a project, you must ensure that the following pre-requisites are fulfilled:

1. Required APIs are activated

    ```
    "iam.googleapis.com",
    "cloudresourcemanager.googleapis.com",
    "iamcredentials.googleapis.com",
    "sts.googleapis.com",
    ```

1. Service Account used to deploy this module has the following roles

    ```
    roles/iam.workloadIdentityPoolAdmin
    roles/iam.serviceAccountAdmin
```
and remove the redirection to the README.md from the [step](https://github.com/suzuki-shunsuke/tfaction/blob/9dfb01f9ebb078e2917d1133b378d552b1791f2c/test-module/action.yaml#L63C14-L63C28)

**Comment by rochana-atapattu** [comment]
also i think you need to add `pull_request_targe` [here](https://github.com/suzuki-shunsuke/tfaction/blob/9dfb01f9ebb078e2917d1133b378d552b1791f2c/test-module/action.yaml#L65)

**Comment by suzuki-shunsuke** [comment]
Thank you for your feedback.
I didn't know the output config.
But I think you can use header-from and footer-from instead of inject mode.

https://github.com/suzuki-shunsuke/tfaction-example/blob/main/templates/module-hello/.terraform-docs.yml

**Comment by suzuki-shunsuke** [comment]
> also i think you need to add `pull_request_targe` [here](https://github.com/suzuki-shunsuke/tfaction/blob/9dfb01f9ebb078e2917d1133b378d552b1791f2c/test-module/action.yaml#L65)

Yeah, that's right. Thank you for pointing it out.

**Comment by rochana-atapattu** [comment]
> Thank you for your feedback. I didn't know the output config. But I think you can use header-from and footer-from instead of inject mode.
> 
> https://github.com/suzuki-shunsuke/tfaction-example/blob/main/templates/module-hello/.terraform-docs.yml

yes but we can use headers and footers to add more general information to the README  which will give more flexibilty to the user
we can also do
```bash
github-comment exec \
    -config "${GITHUB_ACTION_PATH}/github-comment.yaml" \
    -var "tfaction_target:${TFACTION_TARGET}" \
   -- terraform-docs --output-file README.md .
``` 
which will give us the same results without overwritting the README
`--output-file README.md ` override the output.file option in .terraform-docs.yml
and default output mode is inject

**Comment by suzuki-shunsuke** [comment]
> also i think you need to add `pull_request_targe` [here](https://github.com/suzuki-shunsuke/tfaction/blob/9dfb01f9ebb078e2917d1133b378d552b1791f2c/test-module/action.yaml#L65)

- https://github.com/suzuki-shunsuke/tfaction/pull/1583

**Comment by suzuki-shunsuke** [comment]
📝 `--output-file` was added at terraform-docs v0.12.0.

https://github.com/terraform-docs/terraform-docs/releases/tag/v0.12.0

The release date is `Mar 23, 2021`, so there is no problem.

**Comment by suzuki-shunsuke** [comment]
Now test-module runs `terraform-docs` as the following.

https://github.com/suzuki-shunsuke/tfaction/blob/8e6060b0973557b49709ac60f1833709aae77bc9/test-module/action.yaml#L63

```sh
terraform-docs . > README.md
```

If `output` is set as the following, README.md becomes empty.

```yaml
output:
  file: README.md
  mode: inject
```

```console
$ terraform-docs . > README.md
$ cat README.md 
Error: file content is empty
```

On the other hand, `terraform-docs --output-file README.md .` works well.

```console
$ terraform-docs --output-file README.md .
```

But if the comment `<!-- BEGIN_TF_DOCS -->` isn't set, the command fails.

```console
$ terraform-docs --output-file README.md .
Error: begin comment is missing
```

So this is a breaking change.

We can check if the comment exists, and if they don't exist we can run `terraform-docs . > README.md` without `--output-file` option.
This keeps the compatibility, but I'm not sure if it's good.
