### ISSUE TITLE
An error occured `workflow run's headSha () is different from the associated pull request's head sha`

### ISSUE THREAD

**Issue by ponkio-o** [suzuki-shunsuke/tfaction#1594]
### tfaction version

v1.3.0

### Overview

Merging the PR and execute apply fails will result in "workflow run's headSha () is different from the associated pull request's head sha" error.

And I'm using same code of [tfaction-example](https://github.com/suzuki-shunsuke/tfaction-example) in my workflow.

### How to reproduce

tfaction-root.yaml

```yaml
---
plan_workflow_name: test

draft_pr: false # default is false. If `draft_pr` is true, tfaction creates pull requests as draft
base_working_directory: "" # default is empty, which means the current directory
working_directory_file: tfaction.yaml # default is "tfaction.yaml"
conftest_policy_directory: policy/terraform

renovate_login: "renovate[bot]" # default is "renovate[bot]"
label_prefixes:
  target: "target:" # default is "target:"
  tfmigrate: "tfmigrate:" # default is "tfmigrate:"
  skip: "skip:" # default is "skip:"

aqua:
  update_checksum:
    # Update aqua-checksums.json in `setup` action
    enabled: true # default is false
    skip_push: false # default is false
    prune: true # default is false

update_local_path_module_caller:
  enabled: false

tfsec:
  enabled: false
tflint:
  enabled: false
trivy:
  enabled: false

drift_detection:
  enabled: true
  issue_repo_owner: ponkio-o
  issue_repo_name: my-terraform
  num_of_issues: 1
  minimum_detection_interval: 1

terraform_command: terraform

target_groups:
  - working_directory: fastly
    target: fastly
    aws_region: ap-northeast-1
    terraform_command: terraform
    drift_detection:
      enabled: true
    terraform_plan_config:
      aws_assume_role_arn: arn:aws:iam::123412341234:role/github-actions-terraform-plan-role
    terraform_apply_config:
      aws_assume_role_arn: arn:aws:iam::123412341234:role/github-actions-terraform-apply-role
plan_workflow_name: test

draft_pr: false # default is false. If `draft_pr` is true, tfaction creates pull requests as draft
base_working_directory: "" # default is empty, which means the current directory
working_directory_file: tfaction.yaml # default is "tfaction.yaml"

conftest_policy_directory: policy/terraform

renovate_login: "renovate[bot]" # default is "renovate[bot]"
label_prefixes:
  target: "target:" # default is "target:"
  tfmigrate: "tfmigrate:" # default is "tfmigrate:"
  skip: "skip:" # default is "skip:"

aqua:
  update_checksum:
    # Update aqua-checksums.json in `setup` action
    enabled: true # default is false
    skip_push: false # default is false
    prune: true # default is false

update_local_path_module_caller:
  enabled: false

tfsec:
  enabled: false
tflint:
  enabled: false
trivy:
  enabled: false

terraform_command: terraform

target_groups:
  - working_directory: fastly
    target: fastly
    aws_region: ap-northeast-1
    terraform_command: terraform
    drift_detection:
      enabled: true
    terraform_plan_config:
      aws_assume_role_arn: arn:aws:iam::123412341234:role/github-actions-terraform-plan-role
    terraform_apply_config:
      aws_assume_role_arn: arn:aws:iam::123412341234:role/github-actions-terraform-apply-role
    aws_secrets_manager:
      - secret_id: hogehoge
        envs:
          - env_name: FASTLY_API_KEY
            secret_key: FASTLY_API_KEY
```

tfaction.yaml (in fastly/)

```yaml
{}
```

GitHub Actions Workflow

```yaml
---
name: apply
on:
  push:
    branches: [main]
env:
  TFACTION_IS_APPLY: "true"
jobs:
  setup:
    runs-on: ubuntu-latest
    permissions:
      contents: read # For checkout a private repository
      pull-requests: write # For ci-info and github-comment
    outputs:
      targets: ${{ steps.list-targets.outputs.targets }}
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: aquaproj/aqua-installer@7c7338067bdb97d5bea2acc82b5870afca470d18 # v2.3.0
        with:
          aqua_version: v2.24.1

      - uses: suzuki-shunsuke/tfaction/list-targets@ae351c9ff27a0626ce02861db502ce4fb11af71e # v1.3.0
        id: list-targets

  apply:
    name: "apply (${{matrix.target.target}})"
    runs-on: ${{matrix.target.runs_on}}
    needs: setup
    # if services is empty, the build job is skipped
    if: "join(fromJSON(needs.setup.outputs.targets), '') != ''"
    strategy:
      fail-fast: false
      matrix:
        target: ${{fromJSON(needs.setup.outputs.targets)}}
    env:
      TFACTION_TARGET: ${{matrix.target.target}}
      TFACTION_JOB_TYPE: ${{matrix.target.job_type}}
    permissions:
      id-token: write # For OIDC
      contents: read # To checkout a private repository
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Generate token for aqua-installer
        id: aqua_installer_token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
          # If you use private registries, contents:read is required
          permissions: >-
            {}
          # If you use private registries, please add private repositories
          repositories: >-
            []

      - uses: aquaproj/aqua-installer@7c7338067bdb97d5bea2acc82b5870afca470d18 # v2.3.0
        with:
          aqua_version: v2.24.1
        env:
          AQUA_GITHUB_TOKEN: ${{ steps.aqua_installer_token.outputs.token }}

      - uses: suzuki-shunsuke/tfaction/export-secrets@ae351c9ff27a0626ce02861db502ce4fb11af71e # v1.3.0
        with:
          secrets: ${{ toJSON(secrets) }}

      - name: Generate token to download private Terraform Modules
        id: gh_setup_token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
          # If you use private registries, contents:read is required
          permissions: >-
            {
              "contents": "read"
            }
          # private repositories hosting private modules
          repositories: >-
            []

      # This is required to download private modules in `terraform init`
      - run: gh auth setup-git
        env:
          GITHUB_TOKEN: ${{ steps.gh_setup_token.outputs.token }}

      - name: Generate token to update drift issues
        id: drift_issue_token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
          # issues:write - Create and update drift issues
          permissions: >-
            {
              "issues": "write"
            }
          # GitHub Repository where Drift Detection issues are hosted
          # https://suzuki-shunsuke.github.io/tfaction/docs/feature/drift-detection
          repositories: >-
            [
              "my-terraform"
            ]

      - run: tfaction get-or-create-drift-issue
        shell: bash
        env:
          GITHUB_TOKEN: ${{ steps.drift_issue_token.outputs.token }}

      - name: Generate token for setup
        id: setup_token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
          # pull_requests:write - Post comments
          # issues:write - Update drift issues
          permissions: >-
            {
              "pull_requests": "write",
              "issues": "write"
            }
          repositories: >-
            [
              "${{github.event.repository.name}}",
              "my-terraform"
            ]

      - uses: suzuki-shunsuke/tfaction/setup@ae351c9ff27a0626ce02861db502ce4fb11af71e # v1.3.0
        with:
          github_token: ${{ steps.setup_token.outputs.token }}
          ssh_key: ${{ secrets.TERRAFORM_PRIVATE_MODULE_SSH_KEY }} # This isn't needed if you don't use SSH key to checkout private Terraform Modules

      - name: Generate token for apply
        id: apply_token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
          # pull_requests:write - Post comments
          # actions:read - Download plan files
          # issues:write - Update drift issues
          # contents:write - Update related pull requests
          permissions: >-
            {
              "pull_requests": "write",
              "actions": "read",
              "contents": "write",
              "issues": "write"
            }
          repositories: >-
            [
              "${{github.event.repository.name}}",
              "my-terraform"
            ]

      - uses: suzuki-shunsuke/tfaction/apply@ae351c9ff27a0626ce02861db502ce4fb11af71e # v1.3.0
        with:
          github_token: ${{ steps.apply_token.outputs.token }}

      - name: Generate token for creating follow up pr
        id: follow_up_pr_token
        if: failure()
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
          # contents:write - Push commits
          # pull_requests:write - Create a pull request
          permissions: >-
            {
              "contents": "write",
              "pull_requests": "write"
            }
          repositories: >-
            [
              "${{github.event.repository.name}}"
            ]

      - uses: suzuki-shunsuke/tfaction/create-follow-up-pr@ae351c9ff27a0626ce02861db502ce4fb11af71e # v1.3.0
        if: failure()
        with:
          github_token: ${{steps.follow_up_pr_token.outputs.token}}

      - uses: suzuki-shunsuke/tfaction/update-drift-issue@ae351c9ff27a0626ce02861db502ce4fb11af71e # v1.3.0
        if: always()
        with:
          status: ${{job.status}}
          github_token: ${{steps.drift_issue_token.outputs.token}}
```

GitHub Actions' log

```
Run suzuki-shunsuke/tfaction/apply@ae351c9ff27a0626ce02861db502ce4fb11af71e
Run suzuki-shunsuke/tfaction/terraform-apply@v1.3.0
Run suzuki-shunsuke/tfaction/get-target-config@v1.3.0
Run suzuki-shunsuke/tfaction/get-global-config@v1.3.0
Run suzuki-shunsuke/tfaction/check-terraform-skip@v1.3.0
Run bash /home/runner/work/_actions/suzuki-shunsuke/tfaction/v1.3.0/terraform-apply/main.sh
Error: workflow run's headSha () is different from the associated pull request's head sha (8e98e54ecbd1ead5c19106b6250106a536abd4a1)
Error: Process completed with exit code 1
```

### Expected behaviour

'apply' must be done successfully.

### Actual behaviour

An error "workflow run's headSha () is different from the associated pull request's head sha" occured.

### Important Factoids

- I'm using "merge commits"
- The same issue occured when merged follow up PR (created by tfaction) 

### Note

If my understanding is correct, perhaps a commit that is not a merge commit is set as head SHA?
```
Error: workflow run's headSha () is different from the associated pull request's head sha (8e98e54ecbd1ead5c19106b6250106a536abd4a1)
```
![CleanShot 2024-03-17 at 15 57 05](https://github.com/suzuki-shunsuke/tfaction/assets/29038315/f1b378df-e9e2-445d-ae09-6869d30cdbde)
