### ISSUE TITLE
Extra whitespace detected at the end of targets in list-target job

### ISSUE THREAD

**Issue by cappyzawa** [suzuki-shunsuke/tfaction#1661]
### tfaction version

v1.3.2

### Overview

Occasionally, the list-target job detects targets with extra whitespace at the end. Upon investigating, I discovered that in the follow-up PR body, `\n` is sometimes treated as `\r\n`. 
The reason for this behavior is unclear.
When the newline character is `\r\n`, extra whitespace remains even after ` -->` is removed from the end of the first line in the PR body.

### How to reproduce

tfaction-root.yaml

```yaml
plan_workflow_name: test
scaffold_working_directory:
  skip_adding_aqua_packages: true
target_groups:
- working_directory: one
  target: one
```

tfaction.yaml

```yaml
{}
```

GitHub Actions Workflow

```yaml
name: plan
on:
  pull_request:
    branches: [main]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  TFACTION_IS_APPLY: "false"
permissions:
  id-token: write
  contents: read
  pull-requests: write
jobs:
  list-targets:
    runs-on: ubuntu-latest
    outputs:
      targets: ${{ steps.list-targets.outputs.targets }}
    steps:
    - uses: actions/checkout@v4.1.1
    - uses: aquaproj/aqua-installer@v3.0.0
      with:
        aqua_version: v2.25.1

    - uses: suzuki-shunsuke/tfaction/list-targets@v1.3.2
      id: list-targets
```

Other related code such as local Registry

```

```

GitHub Actions' log

```
Run suzuki-shunsuke/tfaction/list-targets-with-changed-files@v1.3.2
targets: [{"target":"one","runs_on":"ubuntu-latest","job_type":"terraform"},{"target":"one ","runs_on":"ubuntu-latest","job_type":"terraform"}]
```

PR comment
```
<!-- tfaction follow up pr target=one -->
@cappyzawa
```

### Expected behaviour

The list-target job should not detect any targets with extra whitespace at the end.

### Actual behaviour

Sometimes the list-target job inadvertently detects targets with extra whitespace at their end.

### Note

The job that confirmed that `\r\n` is included as a newline code is https://github.com/cappyzawa/tfaction-debug/actions/runs/8934424916/job/24541344967.
