### ISSUE TITLE
Request for Support to Create Follow-Up PRs for Drift Detection

### ISSUE THREAD

**Issue by cappyzawa** [suzuki-shunsuke/tfaction#1704]
### Feature Overview

Request for support to create follow-up PRs for drift detection.

### Why is the feature needed?

Currently, drift detection in tfaction creates GitHub Issues to track detected drifts. 
While this is useful, it would be more efficient for our workflow if follow-up PRs were automatically created when a drift is detected. 

Having the option to choose between managing drifts via Issues or follow-up PRs would cater to different workflow preferences and enhance flexibility.

### Example Code

GitHub Actions

```yaml
    steps:
    - uses: actions/checkout@v4.1.1
    - uses: tibdex/github-app-token@v1.9.0
      id: generate_token
      with:
        app_id: ${{ secrets.APP_ID }}
        private_key: ${{ secrets.APP_PRIVATE_KEY }}
    - uses: aquaproj/aqua-installer@v3.0.0
      with:
        aqua_version: v2.25.1
    - uses: suzuki-shunsuke/tfaction/export-secrets@v1.5.0
      with:
        secrets: ${{ toJSON(secrets) }}
    - uses: suzuki-shunsuke/tfaction/setup@v1.5.0
      id: setup
      with:
        github_token: ${{ steps.generate_token.outputs.token }}
    - uses: suzuki-shunsuke/tfaction/test@v1.5.0
      with:
        github_token: ${{ steps.generate_token.outputs.token }}
    - uses: suzuki-shunsuke/tfaction/plan@v1.5.0
      with:
        github_token: ${{ steps.generate_token.outputs.token }}
      env:
        TF_VAR_github_app_token: ${{ steps.generate_token.outputs.token }}
        TFACTION_DRIFT_ISSUE_NUMBER: 0 # This is set to detect drift but ideally should not reference an issue
    - uses: suzuki-shunsuke/tfaction/create-follow-up-pr@v1.5.0
      if: failure()
      with:
        github_token: ${{ steps.generate_token.outputs.token }}
```
