### ISSUE TITLE
Allow `runs_on` to be configured in tfaction.yaml

### ISSUE THREAD

**Issue by florianmutter** [suzuki-shunsuke/tfaction#1713]
### Feature Overview

Right now runs_on has to be configured in `tfaction-root.yaml`. We would like to configure it in `tfaction.yaml`.

### Why is the feature needed?

 To be more flexible without needing to create new target groups.

### Example Code

GitHub Actions

```yaml

```

tfaction-root.yaml

```yaml
  - working_directory: infrastructure/terraform/
    # Use folder path below infrastructure/terraform/ for labels. Can be removed when https://github.com/suzuki-shunsuke/tfaction/issues/1502 is fixed
    target: ""
```

tfaction.yaml

```yaml
runs_on: ubuntu-latest

```
