### ISSUE TITLE
Using Taskfile as terraform Wrapper with tfaction GitHub Actions

### ISSUE THREAD

**Issue by NikitaCOEUR** [suzuki-shunsuke/tfaction#1714]
### tfaction version

`v1.5.1`

### Overview

I've created a command wrapper using Taskfile, allowing the execution of the command `task terraform -- <terraform args>` to run Terraform commands by loading environment variables based on the working directories. This setup enables me to define different environment variables depending on the working directory context, centralize the reference to these variables, and ensure they are set when someone runs Terraform commands.

I am currently setting up a CI based on tfaction GitHub Actions. I want the context of the Terraform commands to be the same whether we execute Terraform commands on our machine or through the CI.

### How to reproduce

tfaction-root.yaml

```yaml
terraform_command: "task terraform --"

target_groups:
- working_directory: terraform/
  target: terraform
```

tfaction.yaml

```yaml
{}
```

aqua.yaml : 

```yaml
packages:
- name: go-task/task@v3.37.2

``` 

.env.taskfile

```
TF_VAR_variable=TEST
```

Taskfile.yml

```yaml
# https://taskfile.dev

version: '3'

tasks :
  terraform:
    desc: Run terraform command with wrapper env
    aliases:
      - tf
    summary: |
      Run terraform command with wrapper env
      Examples :
      - Initialise terraform :
        > task tf -- init
      - Plan terraform :
        > task tf -- plan
      - Apply terraform :
        > task tf -- apply
    preconditions:
      - sh: "command -v terraform"
    dir: "{{.PUG_WORKING_DIRECTORY | default .USER_WORKING_DIR}}"
	dotenv: {{.ROOT_DIR/.env.taskfile}} # This load .env.taskfile as env var
    cmds:
      - terraform {{.CLI_ARGS}}
```

terraform/directory/main.tf

```tf
variable "variable" {
  type        = string
  sensitive   = false
}


resource "terraform_data" "test" {
    input = {
        test = var.variable
    }
}

```

### Expected behaviour

When making a terraform plan on my laptop : 

``` 
task tf -- plan

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following
symbols:
  + create

Terraform will perform the following actions:

  # terraform_data.test will be created
  + resource "terraform_data" "test" {
      + id     = (known after apply)
      + input  = {
          + test = "test"
        }
      + output = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

``` 

### Actual behaviour

But with tfaction, all related terraform command are launched by this way (eg):
https://github.com/suzuki-shunsuke/tfaction/blob/main/terraform-plan/main.sh#L15-L16
```
"$TF_COMMAND" plan -no-color -detailed-exitcode -out tfplan.binary -input=false $opts
```
or 
https://github.com/suzuki-shunsuke/github-action-terraform-init/blob/main/main.sh
```
[...]
  github-comment exec -- "$TF_COMMAND" init -input=false
[...]
"$TF_COMMAND" init -input=false || github-comment exec -- "$TF_COMMAND" init -input=false -upgrade
[...]
```

Result : 
```
Run bash /home/runner/work/_actions/suzuki-shunsuke/github-action-terraform-init/71673ab29266f67c4470773675e087e9a4dda3c5/main.sh
/home/runner/work/_actions/suzuki-shunsuke/github-action-terraform-init/71673ab29266f67c4470773675e087e9a4dda3c5/main.sh: line 15: task terraform --: command not found
run a command: exec: "task terraform --": executable file not found in $PATH
Error: Process completed with exit code 255.
```

Surrounded quotes of $TF_COMMAND force usage of a binary without any args so i can't specify "task terraform --"

### Note

Is this an intended behavior?

Because maybe we can specify an array of commands in tfaction-root.yaml: 
```
terraform_command:
 - 'task'
 - 'terraform'
 - '--'
```

and replace `"$TF_COMMAND"` with `"${TF_COMMAND[@]}"` ?

I tried a workaround by establishing a bash alias: task-terraform=task terraform -- but without success, the alias did not pass through the steps
