### ISSUE TITLE
Use array of tags to select specific self hosted github runners as "runs-on"

### ISSUE THREAD

**Issue by NikitaCOEUR** [suzuki-shunsuke/tfaction#1738]
### Feature Overview

Currently, tfaction allows configuration via the tfaction-root.yml file at the root of the project. The runs-on property in GitHub Actions can be set to either a string or an array to specify the runner for a job, as detailed in the [GitHub documentation](https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners/using-self-hosted-runners-in-a-workflow#using-custom-labels-to-route-jobs). However, tfaction does not support defining an array of strings for the runs-on property, making it impossible to select a runner using tags.

### Why is the feature needed?

Adding support for an array of strings in the runs-on property would allow more precise runner selection through tags, enhancing the flexibility and configurability of GitHub Actions workflows. This feature is essential for projects that require specific runners with custom labels, ensuring that jobs are executed in the desired environment. (For example, we have multiple datacenter with runners wich have access to specifics ressources).

### Example Code

tfaction-root.yaml

```yaml
plan_workflow_name: test

target_groups:
- working_directory: terraform/env-TF-ACTION-TEST
  target: TF-ACTION-TEST
  environment: TF-ACTION-TEST
  runs_on: 
    - self-hosted
    - linux
    - france
  secrets: # GitHub Secrets
  - env_name: AWS_ACCESS_KEY_ID
    secret_name: BACKEND_ACCESS_KEY_ID
  - env_name: AWS_SECRET_ACCESS_KEY 
    secret_name: BACKEND_SECRET_KEY
- working_directory: terraform/env-TF-ACTION-TEST2
  target: TF-ACTION-TEST2
  environment: TF-ACTION-TEST2
  runs_on: 
    - self-hosted
    - linux
    - japan
  secrets: # GitHub Secrets
  - env_name: AWS_ACCESS_KEY_ID
    secret_name: BACKEND_ACCESS_KEY_ID
  - env_name: AWS_SECRET_ACCESS_KEY 
    secret_name: BACKEND_SECRET_KEY
- working_directory: terraform/global
  target: global
  runs_on: ubuntu-latest
  secrets: # GitHub Secrets
  - env_name: AWS_ACCESS_KEY_ID
    secret_name: BACKEND_ACCESS_KEY_ID
  - env_name: AWS_SECRET_ACCESS_KEY 
    secret_name: BACKEND_SECRET_KEY

```

### Note

This enhancement aligns tfaction with GitHub Actions' capabilities, providing users with the ability to utilize self-hosted runners effectively. It is critical for scenarios where specific hardware or configurations are needed, which are often tagged with multiple labels.
