### ISSUE TITLE
Support running Conftest on *.tf and *.tf.json before running `terraform plan`

### ISSUE THREAD

**Issue by suzuki-shunsuke** [suzuki-shunsuke/tfaction#1750]
## Feature Overview

Support running Conftest on *.tf and *.tf.json before running `terraform plan`.

## Why is the feature needed?

tfaction has already supported running Conftest on Terraform plan files.

https://suzuki-shunsuke.github.io/tfaction/docs/feature/conftest

But as mentioned in the following blog post, some policies should be run before running `terraform plan` for security.

https://engineering.mercari.com/en/blog/entry/20230706-bucket-full-of-secrets-terraform-exfiltration/

So this issue proposes to support running Conftest on *.tf and *.tf.json before running terraform plan.

## Example Code

By default, this feature is disabled.
To use this feature, you have to configure it in tfaction-root.yaml.

e.g. tfaction-root.yaml

```yaml
conftest:
  hcl_policy: policy/hcl
  hcl_combine_policy: policy/hcl-combine
```

`hcl_policy` is a path to policy directory.
`hcl_combine_policy` is also a path to policy directory, but this policy is for [--combine](https://www.conftest.dev/options/#-combine) option.

## Do we need to run Conftest on both plan files and *.tf and *.tf.json?

Yes, we think

1. Basically, we should run Conftest on plan files
2. We should also run Conftest on *.tf and *.tf.json for Policies which can't be run on plan files or should be run before `terraform plan`

For example, plan files don't include the information about Terraform Backend.
If you want to apply policies about Terraform Backend, you need to apply them on *.tf and *.tf.json.

## Note

- https://zenn.dev/shunsuke_suzuki/scraps/53d7f5e954f90d
- https://engineering.mercari.com/en/blog/entry/20230706-bucket-full-of-secrets-terraform-exfiltration/

**Comment by suzuki-shunsuke** [comment]
tfaction-root.yaml:

```yaml
conftest:
  hcl_policy: policy/hcl
```

**Comment by suzuki-shunsuke** [comment]
We want to support more flexible syntax.
Users may want to run Conftest on other files too.

```yaml
conftest:
  state_policy: policy/state
  state_combine_policy: policy/combine/state
  tf_policy: policy/hcl
  tf_combine_policy: policy/combine/hcl
  others:
    - policy: policy/yaml
      combine_policy: policy/combine/yaml
      patterns:
        - "*.yaml"
        - "*.yml"
```

**Comment by suzuki-shunsuke** [comment]
tfaction-root.yaml

```yaml
conftest:
  policies:
    - policy: policy/state
      state: true
      id: state
    - policy: policy/combine/state
      state: true
      combine: true
      data: data/data.yaml
    - policy: policy/hcl
      tf: true
    - policy: policy/combine/hcl
      tf: true
      combine: true
    - policy: policy/yaml
      patterns:
        - "*.yaml"
        - "*.yml"
        - "!main.yaml"
```

tfaction.yaml

```yaml
conftest:
  disable-all: true
  policies:
    - policy: policy/state
      state: true
    - id: state
      enabled: false
```
