### ISSUE TITLE
Embed the dependency graph by `terraform graph` and Mermaid in documents

### ISSUE THREAD

**Issue by suzuki-shunsuke** [suzuki-shunsuke/tfaction#1862]
### Feature Overview

Embed the dependency graph by `terraform graph` and Mermaid in documents.

### Why is the feature needed?

Dependency graph is useful to understand the infrastructure.

### Example Code

tfaction-yaml

```yaml
docs:
  terraform-docs: true
  dependency-graph: true
```

tfaction.yaml

```yaml
docs:
  terraform-docs: true
  dependency-graph: true
```

### Note

- https://github.com/asannou/tfmermaid-action
