### ISSUE TITLE
More flexible mapping working_directory and target

### ISSUE THREAD

**Issue by suzuki-shunsuke** [suzuki-shunsuke/tfaction#1879]
### Feature Overview

More flexible mapping between working_directory and target.

### Why is the feature needed?

For now, the rule  of mapping between working_directory and target is very simple based on their prefix.
But some users need more flexible mapping rules.
`target` is used in tfcmt's labels, but the length of labels must be less equal than 50, which is a limitation of GitHub.
Sometimes it is difficult to shorten the length of directories, which is a blocker of tfaction.

To solve this issue, we need to introduce more flexible mapping rules.

**Comment by suzuki-shunsuke** [comment]
# Regular expression

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace

```yaml
replace:
  method: js
  patterns:
  - regexp: /staging$
    replace: /stg
  - regexp: /staging/
    replace: /stg/
  - regexp: /foo-(.*)/
    replace: "/$1/"
    flags: g
```

## Downside

This feature converts `working_directory` with `target` flexibly, but it makes hard (or impossible) to convert `target` with `working_directory`.
This harms the feature of `target` labels, but I think we have no choice and we can accept the downside.
