### ISSUE TITLE
Fix code by `tflint --fix`

### ISSUE THREAD

**Issue by suzuki-shunsuke** [suzuki-shunsuke/tfaction#1892]
### Feature Overview

Fix code by `tflint --fix`.

### Why is the feature needed?

Fix code automatically.

### Example Code

tfaction-root.yaml

```yaml
tflint:
  enabled: true
  fix: true
```

tfaction.yaml

```yaml

```

### Note

- https://github.com/suzuki-shunsuke/github-action-tflint/issues/543
