### ISSUE TITLE
Provide additional data to conftest HCL

### ISSUE THREAD

**Issue by rochana-atapattu** [suzuki-shunsuke/tfaction#1896]
### Feature Overview

At the moment I want to ensure that the prefix of the terraform backend
```hcl
terraform {
  backend "gcs" {
    bucket = "state-bucket"
    prefix = "path/to/dir/v1/terraform.tfstate"
  }
}
```
is same as working_directory. I was thinking of passing the jaon from get-target-config to `conftest` as data.

### Why is the feature needed?

This will provide more context to Conftest policies

### Example Code

GitHub Actions

```yaml

```

tfaction-root.yaml

```yaml

```

tfaction.yaml

```yaml

```

### Note

I want to implement this feature and I'm not sure if there's any value adding JSON from get-global-config too, any thought? Also if you have any suggestions on how I should approaching this it would be great, I was thinking of writing the content to a temporary file and passing it in as data to
https://github.com/suzuki-shunsuke/tfaction/blob/e99c8c8058697b6bd90b9cefd36583643001c2c2/conftest-hcl/main.sh#L17

PS: depends on #1750

**Comment by suzuki-shunsuke** [comment]
To pass file paths to Conftest, I think we can use [-combine](https://www.conftest.dev/options/#-combine) option.
Or another unusual way is to generate a file and pass it using [-data](https://www.conftest.dev/options/#-data) option.

Note that `conftest-hcl` hasn't been released yet.
We're working on implementing flexible validation using Conftest now.

- https://github.com/suzuki-shunsuke/tfaction/issues/1750

**Comment by suzuki-shunsuke** [comment]
tfaction v1.8.0 is out 🎉
https://github.com/suzuki-shunsuke/tfaction/releases/tag/v1.8.0

This release has drastically improved Conftest support!
You can use `-combine` and `-data` options, and test not only Terraform Plan files but also Terraform Configuration `*.tf` and `*.tf.json`.

**Comment by rochana-atapattu** [comment]
Thank you, @suzuki-shunsuke, for the update! I really appreciate all the work you're doing on this project. I came across a couple of issues in the release that I wanted to bring to your attention:

- Documentation issue: [This line](https://github.com/suzuki-shunsuke/tfaction-docs/blob/c1f7d8aa18386bf20b41cfa2a0012583ebfef0c6/docs/feature/conftest.md?plain=1#L110) says "A relative path to a data directory from the repository root directory," but from what I noticed, it seems to be actually looking inside the working_directory for the data directory.

- There seems to be an issue with the data handling:
    > ## ❌ platform/zipzap/dev/project-configurations: Violate Conftest Policy
    > 
    > [Build link](https://github.com/codimite-devops/infrastructure/actions/runs/11326460759)
    > 
    > ```
    > $ conftest test --no-color -p /home/runner/work/infrastructure/infrastructure/policy/terraform --data platform/zipzap/dev/project-configurations/data versions.tf variables.tf terraform.tf main.tf
    > ```
    > 
    > Error: running test: load: filter data paths: 1 error occurred during loading: stat platform/zipzap/dev/project-configurations/data: no such file or directory


    my tfaction-root.yaml
    ```yaml
    conftest:
       policies:
        - policy: policy/terraform
           tf: true
           data: data
     ```
     I believe this is happening because we're changing the directory to the working_directory during execution here:
     https://github.com/suzuki-shunsuke/tfaction/blob/daeb3460547e54b16ba31933f7ebdfb2ad2a3a26/conftest/src/run.ts#L167

**Comment by suzuki-shunsuke** [comment]
Oh, thank you for reporting the issue! I'll take a look.

**Comment by suzuki-shunsuke** [comment]
- https://github.com/suzuki-shunsuke/tfaction/pull/1905

> A relative path to a data directory from the repository root directory

The specification is correct, but the implementation is wrong.
I'll fix the bug.

**Comment by suzuki-shunsuke** [comment]
> At the moment I want to ensure that the prefix of the terraform backend is same as working_directory

BTW, I think you can validate GCS Backend prefix without `-data` opiton.

e.g.

```yaml
conftest:
  policies:
    - policy: policy/combine/tf
      tf: true
      combine: true # Use -combine option
```

policy/combine/tf/backend.rego:

```rego
package main

deny_gcs_backend_prefix[msg] {
	file = input[_]
	prefix = file.contents.terraform[_].backend.gcs.prefix
	not startswith(prefix, concat("", [regex.replace(file.path, "/[^/]+$", ""), "/v1"]))
	msg = sprintf("%s: prefix=%s, file=%s", ["Terraform GCS Backend prefix must be <service directory>/v1/terraform.tfstate", prefix, file.path])
}
```

**Comment by rochana-atapattu** [comment]
`file.path` only has the necessary data (path prefix) if we run Conftest from root dir 
> TRAC   | | Unify {"contents": {"terraform": {"backend": {"gcs": {"bucket": "state-bucket", "prefix": "platform/zipzap/dev/project-configuratio/v1/terraform.tfstate"}}}}, "path": "platform/zipzap/dev/project-configurations/terraform.tf"} = file

otherwise its just
> ﻿TRAC   | | Unify {"contents": {"terraform": {"backend": {"gcs": {"bucket": "state-bucket", "prefix": "platform/zipzap/dev/project-configurations/v1/terraform.tfstate"}}}}, "path": "terraform.tf"} = file

**Comment by suzuki-shunsuke** [comment]
Oh, sorry. My bad.
tfaction runs conftest on a working directory because maybe Conftest is managed by aqua.yaml in each working directory.
But maybe we should run conftest on the repository root directory.

Another idea is to let tfaction generate and pass a special data file, including data such as working directory and target.

```yaml
tfaction:
  target: github/foo
  working_directory: github/services/foo
```

Then you can access these data:

```rego
import data.tfaction

wd := tfaction.working_directory
```

I mean tfaction generates and passes the data file automatically so users don't have to do this themselves.

**Comment by suzuki-shunsuke** [comment]
📝 Multiple `-data` options are available.

https://github.com/open-policy-agent/conftest/blob/36fb3670a185058097d319b507f40733689f42bb/internal/commands/test.go#L186

```go
	cmd.Flags().StringSliceP("data", "d", []string{}, "A list of paths from which data for the rego policies will be recursively loaded")

```

**Comment by suzuki-shunsuke** [comment]
📝  `contest test` has various options.
tfaction should support them.

https://github.com/open-policy-agent/conftest/blob/36fb3670a185058097d319b507f40733689f42bb/internal/commands/test.go#L87-L107

https://github.com/open-policy-agent/conftest/blob/36fb3670a185058097d319b507f40733689f42bb/internal/commands/test.go#L164-L189

```yaml
conftest:
  policies:
    - policy: # array or string
        - policy/terraform
      plan: true
      fail_on_warn: true
      no_fail: true
      all_namespaces: true
      quiet: true
      trace: true
      strict: true
      show_builtin_errors: true
      junit_hide_message: true
      suppress_exceptions: true
      ignore: ""
      parser: ""
      capabilities: ""
      output: ""
      namespaces:
        - ""
      tls: true
      proto_file_dirs:
        - ""
      data:
        - ""
      # update: ""
```
