### ISSUE TITLE
The conftest being run in test-module fails

### ISSUE THREAD

**Issue by semnil** [suzuki-shunsuke/tfaction#1908]
### tfaction version

v1.8.0

### Overview

I have not configure `target_groups` in the directory where `tfaction_module.yaml` is located, but it seems that an exception is being generated when trying to read this setting.

### How to reproduce

tfaction-root.yaml

```yaml
contest:
  disable_all: true
```

tfaction_module.yaml

```yaml
{}
```

GitHub Actions Workflow

```yaml
      - uses: suzuki-shunsuke/tfaction/test-module@4fdef7854d0ba89602f5901cbd3df82b5413ab10 # v1.8.0
        with:
          github_token: ${{steps.generate_token.outputs.token}}
        env:
          AQUA_GITHUB_TOKEN: ${{github.token}}
```

Other related code such as local Registry

```

```

GitHub Actions' log

```
Run suzuki-shunsuke/tfaction/test-module@4fdef7854d0ba89602f590[1](https://github.com/quipper/urey-infra/actions/runs/11355586403/job/31585221881#step:7:1)cbd3df82b5413ab10
Run suzuki-shunsuke/tfaction/get-global-config@v1.8.0
Run suzuki-shunsuke/tfaction/conftest@v1.[8](https://github.com/quipper/urey-infra/actions/runs/11355586403/job/31585221881#step:7:9).0
Run node "$GITHUB_ACTION_PATH/dist/index.js"
/home/runner/work/_actions/suzuki-shunsuke/tfaction/v1.8.0/conftest/dist/index.js:60444
            throw new Error("target config is not found in target_groups");
                  ^

Error: target config is not found in target_groups
    at /home/runner/work/_actions/suzuki-shunsuke/tfaction/v1.8.0/conftest/dist/index.js:60444:19
    at Generator.next (<anonymous>)
    at /home/runner/work/_actions/suzuki-shunsuke/tfaction/v1.8.0/conftest/dist/index.js:60410:71
    at new Promise (<anonymous>)
    at __webpack_modules__.9786.__awaiter (/home/runner/work/_actions/suzuki-shunsuke/tfaction/v1.8.0/conftest/dist/index.js:60406:12)
    at run (/home/runner/work/_actions/suzuki-shunsuke/tfaction/v1.8.0/conftest/dist/index.js:60435:33)
    at main (/home/runner/work/_actions/suzuki-shunsuke/tfaction/v1.8.0/conftest/dist/index.js:60426:[21](https://github.com/quipper/urey-infra/actions/runs/11355586403/job/31585221881#step:7:24))
    at 9407 (/home/runner/work/_actions/suzuki-shunsuke/tfaction/v1.8.0/conftest/dist/index.js:60367:20)
    at __nccwpck_require__ (/home/runner/work/_actions/suzuki-shunsuke/tfaction/v1.8.0/conftest/dist/index.js:720[31](https://github.com/quipper/urey-infra/actions/runs/11355586403/job/31585221881#step:7:35):43)
    at /home/runner/work/_actions/suzuki-shunsuke/tfaction/v1.8.0/conftest/dist/index.js:72051:37

Node.js v20.18.0
```

### Expected behaviour

The execution of conftest is skipped as specified in tfaction-root.yaml.

### Actual behaviour

The conftest is executed and an exception is thrown when it references a nonexistent configuration value.

**Comment by suzuki-shunsuke** [comment]
Thank you for reporting the issue.
I'll take a look.

**Comment by suzuki-shunsuke** [comment]
BTW, probably the usage of `conftest.disable_all` is wrong.

```yaml
contest:
  disable_all: true
```

1. Probably `contest` is a typo of `conftest`. I found typo in the document. I'll fix them. https://github.com/suzuki-shunsuke/tfaction-docs/pull/506
1. `conftest.disable_all` should be used in `.target_groups[].conftest` or `tfaction.yaml`

https://suzuki-shunsuke.github.io/tfaction/docs/feature/conftest

tfaction-root.yaml

```yaml
# conftest:
#   disable_all: true # disable_all has no meaning here.
# ...
target_groups:
  - working_directory: aws/
    # ...
    conftest:
      disable_all: true
```

tfaction.yaml

```yaml
conftest:
  policies:
    - id: plan
      enabled: false
    - policy: policy/combine/tf
      tf: true
      combine: true
      data: data
```
