### ISSUE TITLE
feat: Add feature to configure “role-session-name” in config

### ISSUE THREAD

**Issue by ponkio-o** [suzuki-shunsuke/tfaction#1930]
### Feature Overview

I want to be able to set any `role-session-name` in aws-actions/configure-aws-credentials.

### Why is the feature needed?

Currently, tfaction has a fixed value of `samplerolesession` when execute AssumeRole operation, which is undesirable.
https://github.com/suzuki-shunsuke/tfaction/blob/1f76ed16ff681ff5bff6feaa117f97a39d0b5808/setup/action.yaml#L93

This value is mainly recorded in CloudTrail as the User name. 
![image](https://github.com/user-attachments/assets/060acc63-ec54-447a-afca-30232661949e)

Ideally, different names should be set for different IAM Roles. This makes it easier to track which session performed which operation.

### Example Code

tfaction-root.yaml

```yaml
target_groups:
  - working_directory: fastly
    target: fastly
    aws_region: ap-northeast-1
    terraform_plan_config:
      aws_assume_role_arn: arn:aws:iam::123412341234:role/github-actions-terraform-plan-role
      aws_role_session_name: fastly-plan
    ...
```

expand as follow:
```yaml
- uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
      if: steps.target-config.outputs.aws_assume_role_arn != ''
      with:
        role-to-assume: ${{ steps.target-config.outputs.aws_assume_role_arn }}
        role-session-name: fastly-plan
        aws-region: ${{ steps.target-config.outputs.aws_region }}
```
