### ISSUE TITLE
An error occurred: `Error: No target is found for the working directory` when updating a nested module

### ISSUE THREAD

**Issue by k-saiki** [suzuki-shunsuke/tfaction#1966]
### tfaction version

v1.11.1

### Overview

Using nested modules and update_related_pull_requests enabled, an error occurs indicating that the target does not exist when update a nested module.

```bash
├── env/
│   └── test/
│       ├── main.tf 	# call some-module
│       └── tfaction.yaml
└── modules/
    └── some-module/
    	├── tfaction_module.yaml
    	├── main.tf 	# call nested-module
    	└── nested-module/
        	└── main.tf # update
```

### How to reproduce

tfaction-root.yaml

```yaml
plan_workflow_name: test

update_local_path_module_caller:
  enabled: true

target_groups:
- working_directory: env/test
  target: env/test
  aws_region: ap-northeast-1
  terraform_plan_config:
    aws_assume_role_arn: arn:aws:iam::000000000000:role/role-name
```

tfaction.yaml

```yaml
{}
```

GitHub Actions Workflow

```yaml

```

Other related code such as local Registry

```

```

GitHub Actions' log

```
Run suzuki-shunsuke/tfaction/list-module-callers@v1.11.1
file: {"modules/some-module":["env/test"],"modules/some-module/nested-module":["modules/some-module","env/test"]}
Run suzuki-shunsuke/tfaction/list-targets-with-changed-files@v1.11.1
Error: No target is found for the working directory modules/some-module
```

### Expected behaviour

list-targets-with-changed-files should output `[{"target":"env/test","working_directory":"env/test","runs_on":"ubuntu-latest","job_type":"terraform"}]`

### Actual behaviour

list-targets-with-changed-files fail with `Error: No target is found for the working directory`

### Note

I'm using hachicorp/terraform-config-inspect v0.0.0-20240801114854-6714b46f5fe4.
