### ISSUE TITLE
tfaction/plan で `Error: ENOENT: no such file or directory, open '/labels.txt'` エラーが起きる

### ISSUE THREAD

**Issue by saitotqr** [suzuki-shunsuke/tfaction#1997]
### tfaction version

1.12.0

### Overview

`Error: ENOENT: no such file or directory, open '/labels.txt'` でエラーになってしまう

### How to reproduce

tfaction-root.yaml

```yaml
plan_workflow_name: terraform_ci
label_prefixes:
  skip_create_pr: true
aqua:
  update_checksum:
    enabled: false # default is false
    skip_push: false # default is false
    prune: false # default is false
tfsec:
  enabled: false
tflint:
  enabled: false
trivy:
  enabled: false
drift_detection:
  enabled: false
  issue_repo_owner: xxx
  issue_repo_name: xxx
  num_of_issues: 1
  minimum_detection_interval: 1

terraform_command: terraform

update_related_pull_requests:
  enabled: false

target_groups:
- working_directory: tfenv/stg
  target: stg
  aws_region: ap-northeast-1
  terraform_command: terraform
  drift_detection:
    enabled: false
  terraform_plan_config:
    aws_assume_role_arn: arn:aws:iam::xxx:role/actions_managed_runner_terraform_plan
  terraform_apply_config:
    aws_assume_role_arn: arn:aws:iam::xxx:role/actions_managed_runner_terraform_apply
```

tfaction.yaml

```yaml
{}
```

GitHub Actions Workflow

```yaml
name: WIP

on:
  workflow_dispatch:

concurrency:
  group: terraform_ci_${{ github.ref }}
  cancel-in-progress: true

jobs:
  plan:
    strategy:
      matrix:
        target: ["stg"]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      pull-requests: write

    env:
      TFACTION_JOB_TYPE: terraform
      GH_COMMENT_SHA1: ${{github.sha}}

    steps:
      - uses: actions/checkout@v4.1.1
        with:
          ref: ${{github.sha}}
      - uses: actions/cache@v4.0.1
        with:
          path: ~/.local/share/aquaproj-aqua
          key: v1-aqua-installer-${{runner.os}}-${{runner.arch}}-${{hashFiles('aqua.yaml')}}
          restore-keys: |
            v1-aqua-installer-${{runner.os}}-${{runner.arch}}-
      - uses: aquaproj/aqua-installer@v3.0.1
        with:
          aqua_version: v2.21.0
      - uses: suzuki-shunsuke/tfaction/setup@v1.12.0
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
        env:
          TFACTION_TARGET: ${{matrix.target}}
          TF_CLI_ARGS_init: "-backend-config=ci.config"
      - uses: suzuki-shunsuke/tfaction/plan@v1.12.0
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
        env:
          TFACTION_TARGET: ${{matrix.target}}
          TF_CLI_ARGS_plan: "-var-file=ci.tfvars"
          CI_INFO_PR_AUTHOR: "bot-desu"
```

Other related code such as local Registry

aqua.yml
```
checksum:
  enabled: false
  require_checksum: false
registries:
  - type: standard
    ref: v4.174.0 # renovate: depName=aquaproj/aqua-registry
packages:
  - name: suzuki-shunsuke/github-comment@v6.0.4
  - name: suzuki-shunsuke/ci-info@v2.1.3
  - name: suzuki-shunsuke/tfcmt@v4.9.0
  - name: cli/cli@v2.49.1
  - name: int128/ghcp@v1.13.2

```

GitHub Actions' log

```
Run suzuki-shunsuke/tfaction/setup@v1.12.0
Run suzuki-shunsuke/tfaction/install@v1.12.0
Run echo "config=$GITHUB_ACTION_PATH/aqua.yaml" >> "$GITHUB_OUTPUT"
Run aqua i -l
time="2024-11-08T09:13:19Z" level=info msg="create a symbolic link" aqua_version=2.21.0 command=conftest env=linux/amd64 program=aqua
time="2024-11-08T09:13:19Z" level=info msg="create a symbolic link" aqua_version=2.21.0 command=terraform-config-inspect env=linux/amd64 program=aqua
time="2024-11-08T09:13:19Z" level=info msg="create a symbolic link" aqua_version=2.21.0 command=terraform-docs env=linux/amd64 program=aqua
time="2024-11-08T09:13:19Z" level=info msg="create a symbolic link" aqua_version=2.21.0 command=tfaction env=linux/amd64 program=aqua
time="2024-11-08T09:13:19Z" level=info msg="create a symbolic link" aqua_version=2.21.0 command=tfmigrate env=linux/amd64 program=aqua
Run echo "AQUA_GLOBAL_CONFIG=$GITHUB_ACTION_PATH/aqua.yaml:${AQUA_GLOBAL_CONFIG:-}" >> "$GITHUB_ENV"
Run suzuki-shunsuke/tfaction/get-target-config@v1.12.0
Run suzuki-shunsuke/tfaction/get-global-config@v1.12.0
Run echo "$GLOBAL_CONFIG"
{
  "base_working_directory": ".",
  "working_directory_file": "tfaction.yaml",
  "module_base_directory": ".",
  "module_file": "tfaction_module.yaml",
  "renovate_login": "renovate[bot]",
  "draft_pr": "false",
  "skip_create_pr": "false",
  "plan_workflow_name": "terraform_ci",
  "label_prefix_target": "target:",
  "label_prefix_tfmigrate": "tfmigrate:",
  "label_prefix_skip": "skip:",
  "disable_update_related_pull_requests": "true",
  "update_local_path_module_caller": "false",
  "aqua_update_checksum_enabled": "false",
  "aqua_update_checksum_prune": "false",
  "aqua_update_checksum_skip_push": "false",
  "enable_tfsec": "false",
  "enable_tflint": "false",
  "enable_trivy": "false",
  "terraform_command": "terraform",
  "drift_issue_repo_owner": "xxx",
  "drift_issue_repo_name": "xxx"
}
Run echo "$TARGET_CONFIG"
0s
Run suzuki-shunsuke/tfaction/plan@v1.12.0
  with:
    github_token: ***
  env:
    TFACTION_JOB_TYPE: terraform
    GH_COMMENT_SHA1: 45d54a711af013aa52072eb2e01ac759e6b9ef64
    AQUA_GLOBAL_CONFIG: /home/runner/work/_actions/suzuki-shunsuke/tfaction/v1.12.0/install/aqua.yaml:
    TFACTION_WORKING_DIR: tfenv/stg
    TFACTION_TARGET: stg
    TFACTION_SKIP_ADDING_AQUA_PACKAGES: true
    AWS_DEFAULT_REGION: ap-northeast-1
    AWS_REGION: ap-northeast-1
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
    AWS_SESSION_TOKEN: ***
    TF_CLI_ARGS_plan: -var-file=ci.tfvars
    CI_INFO_PR_AUTHOR: bot-desu
Run suzuki-shunsuke/tfaction/terraform-plan@v1.12.0
  with:
    github_token: ***
  env:
    TFACTION_JOB_TYPE: terraform
    GH_COMMENT_SHA1: 45d54a711af013aa52072eb2e01ac759e6b9ef64
    AQUA_GLOBAL_CONFIG: /home/runner/work/_actions/suzuki-shunsuke/tfaction/v1.12.0/install/aqua.yaml:
    TFACTION_WORKING_DIR: tfenv/stg
    TFACTION_TARGET: stg
    TFACTION_SKIP_ADDING_AQUA_PACKAGES: true
    AWS_DEFAULT_REGION: ap-northeast-1
    AWS_REGION: ap-northeast-1
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
    AWS_SESSION_TOKEN: ***
    TF_CLI_ARGS_plan: -var-file=ci.tfvars
    CI_INFO_PR_AUTHOR: bot-desu
Run suzuki-shunsuke/tfaction/get-target-config@v1.12.0
  env:
    TFACTION_JOB_TYPE: terraform
    GH_COMMENT_SHA1: 45d54a711af013aa52072eb2e01ac759e6b9ef64
    AQUA_GLOBAL_CONFIG: /home/runner/work/_actions/suzuki-shunsuke/tfaction/v1.12.0/install/aqua.yaml:
    TFACTION_WORKING_DIR: tfenv/stg
    TFACTION_TARGET: stg
    TFACTION_SKIP_ADDING_AQUA_PACKAGES: true
    AWS_DEFAULT_REGION: ap-northeast-1
    AWS_REGION: ap-northeast-1
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
    AWS_SESSION_TOKEN: ***
    TF_CLI_ARGS_plan: -var-file=ci.tfvars
    CI_INFO_PR_AUTHOR: bot-desu
Run suzuki-shunsuke/tfaction/get-global-config@v1.12.0
  env:
    TFACTION_JOB_TYPE: terraform
    GH_COMMENT_SHA1: 45d54a711af013aa52072eb2e01ac759e6b9ef64
    AQUA_GLOBAL_CONFIG: /home/runner/work/_actions/suzuki-shunsuke/tfaction/v1.12.0/install/aqua.yaml:
    TFACTION_WORKING_DIR: tfenv/stg
    TFACTION_TARGET: stg
    TFACTION_SKIP_ADDING_AQUA_PACKAGES: true
    AWS_DEFAULT_REGION: ap-northeast-1
    AWS_REGION: ap-northeast-1
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
    AWS_SESSION_TOKEN: ***
    TF_CLI_ARGS_plan: -var-file=ci.tfvars
    CI_INFO_PR_AUTHOR: bot-desu
Run suzuki-shunsuke/tfaction/check-terraform-skip@v1.12.0
  with:
    labels: /labels.txt
    pr_author: bot-desu
    skip_label_prefix: skip:
  env:
    TFACTION_JOB_TYPE: terraform
    GH_COMMENT_SHA1: 45d54a711af013aa52072eb2e01ac759e6b9ef64
    AQUA_GLOBAL_CONFIG: /home/runner/work/_actions/suzuki-shunsuke/tfaction/v1.12.0/install/aqua.yaml:
    TFACTION_WORKING_DIR: tfenv/stg
    TFACTION_TARGET: stg
    TFACTION_SKIP_ADDING_AQUA_PACKAGES: true
    AWS_DEFAULT_REGION: ap-northeast-1
    AWS_REGION: ap-northeast-1
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
    AWS_SESSION_TOKEN: ***
    TF_CLI_ARGS_plan: -var-file=ci.tfvars
    CI_INFO_PR_AUTHOR: bot-desu
Error: ENOENT: no such file or directory, open '/labels.txt'
```

### Expected behaviour

plan結果がpr commentに投稿される

### Actual behaviour

`tfaction/plan` で以下のエラーが発生しました。

```
Run suzuki-shunsuke/tfaction/check-terraform-skip@v1.5.1
Error: Input required and not supplied: pr_author
```
check-terraform-skip の pr_authorがrequiredのため、適当な  `env.CI_INFO_PR_AUTHOR` を設定すると以下のエラーになります。
```
Run suzuki-shunsuke/tfaction/check-terraform-skip@v1.12.0
Error: ENOENT: no such file or directory, open '/labels.txt'
```

### Note

ci-info が pullRequestの情報をうまく保存できておらず、labels.txtが生成されていないようです。
`tfaction/plan` の前に以下のstepを差し込んで、回避できることが確認できました。
```
      - name: "ci-info prepare"
        run: |
          ci-info run --github-token ${{secrets.GITHUB_TOKEN}}
          eval "$(ci-info run --github-token ${{secrets.GITHUB_TOKEN}})"
          echo "CI_INFO_TEMP_DIR $CI_INFO_TEMP_DIR"
          cat $CI_INFO_TEMP_DIR/labels.txt
          ci-info run --github-token ${{secrets.GITHUB_TOKEN}} | sed "s/^export //" >> "$GITHUB_ENV"
```
