### ISSUE TITLE
tflintが0.54.0以上でgithub-action-tflintの実行に失敗する

### ISSUE THREAD

**Issue by KimotoYanke** [suzuki-shunsuke/tfaction#2001]
### tfaction version

1.12.0

### Overview

tflintが0.54.0以上のとき、以下のエラーが発生してgithub-action-tflintの実行に失敗します
```
Run suzuki-shunsuke/github-action-tflint@0b7fbc35b0d512749f35c3036df57c3a95d3e9e1
```

```
/home/runner/.local/share/aquaproj-aqua/bin/tflint --format json --module
{"issues":[],"errors":[{"message":"Failed to parse CLI options; --module option was removed in v0.54.0. Use --call-module-type=all instead","severity":"error"}]}Parsing tflint result
Error: Cannot read properties of undefined (reading 'filename')
```

### How to reproduce

ほぼexampleで発生するはずですが、社内用リポジトリでしか再現できておらず一旦部分記述にさせてくださいmm

GitHub Actions Workflow

```yaml
jobs:
  plan:
    steps:
      - uses: suzuki-shunsuke/tfaction/setup@83e231ae2a2d2da48105f2ef9d6095964f70cd29 # v1.12.0
        id: setup
        with:
          github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
      - uses: suzuki-shunsuke/tfaction/test@83e231ae2a2d2da48105f2ef9d6095964f70cd29 # v1.12.0
        with:
          github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
```

### Expected behaviour

エラーなくgithub-action-tflintが実行され、tflintが判定される

### Actual behaviour

`Failed to parse CLI options; --module option was removed in v0.54.0. Use --call-module-type=all instead`というエラーのため`Error: Cannot read properties of undefined (reading 'filename')`というエラーで終了する

### Note

原因はtflintが0.54.0で--moduleオプションを削除したため。
しばらくdeprecatedとしてwarning付きで置いておいてあったので、github-action-tflintにはすでに修正パッチが入っていたものの、github-action-tflintがリリースされておらず、tfactionも修正後のバージョンに向いていなかった。
https://github.com/suzuki-shunsuke/github-action-tflint/pull/1065

そのため、github-action-tflintをリリースしtfactionが向くバージョンを最新にできれば修正できると思われます
