### ISSUE TITLE
Unify JavaScript actions into a single action

### ISSUE THREAD

**Issue by suzuki-shunsuke** [suzuki-shunsuke/tfaction#2113]
### What

Unify JavaScript actions into a single action.

To keep the compatibility, we replace javascript actions with composite actions executing this action.

e.g. suzuki-shunsuke/tfaction/get-target-config

```yaml
runs:
  using: composite
  steps:
    - uses: suzuki-shunsuke/tfaction/js@latest
      with:
        action: get-target-config
```

### Why

By unifying javascript actions into a single actions:

- We need to build only one action. We don't need to build many actions
  - It makes the build process fast and simple
- It's easy to share codes. We don't need to share codes between multiple actions
  - We don't need to consider the build order
  - We don't need to build lib every time we change it
- We don't need to manage files such as package.json, package-lock.json, tsconfig.json per action
- We don't need to install JavaScript libraries per action
- We don't need to add a huge (over 1,000 lines) package-lock.json when adding a new feature (action)
