### ISSUE TITLE
Make tfaction.yaml optional

### ISSUE THREAD

**Issue by suzuki-shunsuke** [suzuki-shunsuke/tfaction#2127]
### Feature Overview

Fow now you need to add tfaction.yaml on every working directory.
tfaction.yaml is used to identify working directories.
This issue suggests to make tfaction.yaml optional, meaning you don't need to add tfaction.yaml on working directories.

### Why is the feature needed?

Adding tfaction.yaml to all working directories is a bit troublesome.
If you want to introduce tfaction to a Monorepo with many working directories, you would need to disable CI temporarily.

### Example Code

tfaction-root.yaml

e.g.

```yaml
# Filenames that tfaction uses to identifies working directories.
# tfaction identifies directories where one of these files exist.
directory_files:
  - providers.tf
  - terraform.tf
ignore_dirs:
  - modules # Ignore directories
```
