### ISSUE TITLE
`Warning: No files were found with the provided path for tfplan.binary` when using Terragrunt

### ISSUE THREAD

**Issue by Taiki130** [suzuki-shunsuke/tfaction#2132]
### tfaction version

v1.11.1

### Overview

We are encountering an issue while using Terragrunt in combination with OpenTofu.

- Terragrunt version: v0.69.3
- OpenTofu version: v1.8.7
Both are the latest versions at the time of writing.

In the tfaction workflow, after generating a plan file, `actions/upload-artifact` is executed to upload the plan file. However, the following warning is displayed during the upload step:
```
Warning: No files were found with the provided path: ***/tfplan.binary. No artifacts will be uploaded.
```

### How to reproduce

tfaction-root.yaml

```yaml
・
・
・
  - working_directory: ***
    target: ***
    aws_region: ap-northeast-1
    s3_bucket_name_plan_file: ***
    s3_bucket_name_tfmigrate_history: ***
    terraform_plan_config:
      aws_assume_role_arn: arn:aws:iam::***:role/***-tfaction_terraform_plan
    tfmigrate_plan_config:
      aws_assume_role_arn: arn:aws:iam::***:role/***-tfaction_tfmigrate_plan
    terraform_apply_config:
      aws_assume_role_arn: arn:aws:iam::***:role/***-tfaction_terraform_apply
    tfmigrate_apply_config:
      aws_assume_role_arn: arn:aws:iam::***:role/***-tfaction_tfmigrate_apply
    terraform_command: terragrunt
    env:
      TERRAGRUNT_TFPATH: "tofu"
      TERRAGRUNT_LOG_DISABLE: "true"
・
・
・
```

tfaction.yaml

```yaml
{}
```

GitHub Actions Workflow

```yaml
・
・
・
      - uses: suzuki-shunsuke/tfaction/plan@50688bc5e4bf266c7db4b841d348eaff199bff95 # v1.11.1
        with:
          github_token: ${{steps.generate_token.outputs.token}}
        env:
          GITHUB_TOKEN: ${{steps.generate_token.outputs.token}} # For GitHub Provider and tfcmt and github-comment
          TF_CLI_ARGS_plan: "-parallelism=30"
          TF_VAR_github_run_id: ${{ github.run_id }}

```

### Expected behaviour

When using the tfaction workflow with Terragrunt, the Terraform plan file (`tfplan.binary`) should be created in a predictable and accessible directory, allowing the `actions/upload-artifact` step to successfully locate and upload the file.

### Actual behaviour

In the current setup:

- The plan file (`tfplan.binary`) is generated in the `.terragrunt-cache` directory by default, which is Terragrunt's working directory.
- As a result, the `actions/upload-artifact` step fails with the following warning:

```log
Warning: No files were found with the provided path: ***/tfplan.binary. No artifacts will be uploaded.
```

## Likely Cause
- The plan file is generated using the `-out=tfplan.binary` option, as seen in the following script:
  - https://github.com/suzuki-shunsuke/tfaction/blob/main/terraform-plan/main.sh#L16
- When using Terragrunt, the default behavior is to create the tfplan.binary file under the `.terragrunt-cache` directory, which is the working directory for Terragrunt.
- This results in the actions/upload-artifact step failing to locate the plan file because it is not in the expected directory.

## Proposed Solution
- As a workaround, the plan file is moved to the Terragrunt directory after execution using an [after_hook](https://terragrunt.gruntwork.io/docs/features/hooks/).
- For a more fundamental fix, the plan file could be generated with an explicit path by using the `-out=$(pwd)/tfplan.binary` option. This ensures the plan file is created in the current working directory instead of the default `.terragrunt-cache`.

If needed, I would be happy to create a Pull Request to address this issue.
