### ISSUE TITLE
Support for updating local modules when using Terragrunt

### ISSUE THREAD

**Issue by Taiki130** [suzuki-shunsuke/tfaction#2145]
### Feature Overview

Currently, the system supports updating local modules when using Terraform, but it does not support updating local modules when using Terragrunt.

### Why is the feature needed?

When updating local modules in Terragrunt, the changes are not detected, and the plan is not triggered. 

### Note

Alternatively, enabling the ability to configure dependencies on directories or files related to the target could provide a viable alternative solution.

tfaction-root.yaml
```yaml
  - working_directory: foo/bar
    target: foo/bar
    extra_dependencies:
      - modules
```
