### ISSUE TITLE
Enable to limit the number of changed working directories and modules in one pull request

### ISSUE THREAD

**Issue by suzuki-shunsuke** [suzuki-shunsuke/tfaction#2743]
### Feature Overview

Enable to limit the number of working directories and modules processed in one workflow run.

### Why is the feature needed?

You shouldn't fix many working directories and modules in the same pull request.

- It's hard to review changes. You may miss unexpected changes
- CI becomes unstable
  - API rate limit
- Inefficient
  - If you fix a directory, you need to run CI on all changed directories
 - Changes can be blocked due to a directory
   - If a directory has some trouble like drift, you can't merge the pull request

### Example Code

tfaction can validate the number of changed directories at list-target action.

tfaction-root.yaml

```yaml
limit_changed_dirs:
  working_dirs: 10 # If the number is 0, no limit
  modules: 10 # If the number is 0, no limit
```
