### ISSUE TITLE
Does it already supported the tfaction config about the tfstate directory and tfvars?

### ISSUE THREAD

**Issue by sahya** [suzuki-shunsuke/tfaction#661]
## Question
Does it already supported the tfaction config about the tfstate directory([tfbackend](https://developer.hashicorp.com/terraform/language/values/variables#variable-definitions-tfvars-files)) and [tfvars](https://developer.hashicorp.com/terraform/language/values/variables#variable-definitions-tfvars-files)?
Or, Should I use another method like [Terraform Backends](https://github.com/hashicorp/terraform-github-actions/blob/master/examples/backends.md).

## Expectation
* Load the backend location by configuration
* Load the file path of the environment variable

## Why
I created a dynamically changing mechanism by Makefile for development and test. So I would like to implement to do similar things like following commands.
* `make init`: `terraform init -backend-config="terraform/$(Namespace)/$(short_env).state"`
* `make plan`: `terraform plan input=false refresh=true -var-file="$(VARS)""`
   e.g. [[GitHub]pgporada/terraform-makefile/Makefile](https://github.com/pgporada/terraform-makefile/blob/master/Makefile)

**Comment by suzuki-shunsuke** [comment]
Thank you for your question.

tfaction supports setting environment variables in `tfaction-root.yaml` and `tfaction.yaml`.

- https://github.com/suzuki-shunsuke/tfaction/issues/420
- https://github.com/suzuki-shunsuke/tfaction/pull/421

And you can configure Terraform with environment variables.

- https://suzuki-shunsuke.github.io/tfaction/docs/config/terraform-cli-options
- https://developer.hashicorp.com/terraform/cli/config/environment-variables#tf_cli_args-and-tf_cli_args_name

Does that answer your question?

**Comment by sahya** [comment]
> Does that answer your question?

Yes, it will be helpful for me. I would try this feature later.
Thank you so much!

For now, I will close this issue(question). If I would have a question, I would ask about it again.

**Comment by sahya** [comment]
@suzuki-shunsuke 
Sorry to reopen my question.
I just confirmed the dynamic variable could not expand in `tfaction.yml`.

Could I define a dynamic variable in `tfaction.yml`? Or I might be wrong about the writing method in `tfaction.yml`?

For example, if the YAML has the following configuration as a example.
`tfaction.yml`:
```yaml
env:
  NAMESPACE: development
  SHORT_ENV: dev
  TF_CLI_ARGS_init:  -backend-config=terraform/$NAMESPACE/$SHORT_ENV.state
```

**Comment by suzuki-shunsuke** [comment]
tfaction doesn't expand variables in `env`'s value.
I can't understand what you want well, but there are three options.

1. Replace variables in `TF_CLI_ARGS_init` yourself

```yaml
env:
  NAMESPACE: development
  SHORT_ENV: dev
  TF_CLI_ARGS_init:  -backend-config=terraform/development/dev.state
```

2. Set variables dynamically after `setup` job

https://github.com/suzuki-shunsuke/tfaction-example/blob/9aa42250f5a9fb8ca996f95d272f36b1a0c1e406/.github/workflows/test.yaml#L151-L158

```yaml
env:
  NAMESPACE: development
  SHORT_ENV: dev
```

```yaml
      - uses: suzuki-shunsuke/tfaction/setup@v0.5.21
        with:
          github_app_token: ${{ steps.generate_token.outputs.token }}

      - run: echo "TF_CLI_ARGS_init=-backend-config=terraform/$NAMESPACE/$SHORT_ENV.state" >> "$GITHUB_ENV"

      - uses: suzuki-shunsuke/tfaction/test@v0.5.21
        with:
          github_app_token: ${{ steps.generate_token.outputs.token }}
```

But the option 2 has a problem that `TF_CLI_ARGS_init` can't set after `setup` job because `terraform init` is run in `setup` job.

3. Run `suzuki-shunsuke/tfaction/get-target-config` and set `TF_CLI_ARGS_init` before `setup` job

So if you want to set `TF_CLI_ARGS_init` dynamically, you have to run `suzuki-shunsuke/tfaction/get-target-config` and set `TF_CLI_ARGS_init` before `setup` job.

```yaml
      - uses: suzuki-shunsuke/tfaction/get-target-config@v0.5.21
      - run: echo "TF_CLI_ARGS_init=-backend-config=terraform/$NAMESPACE/$SHORT_ENV.state" >> "$GITHUB_ENV"

      - uses: suzuki-shunsuke/tfaction/setup@v0.5.21
        with:
          github_app_token: ${{ steps.generate_token.outputs.token }}

      - uses: suzuki-shunsuke/tfaction/test@v0.5.21
        with:
          github_app_token: ${{ steps.generate_token.outputs.token }}
```

I don't test these code yet, but it should work.
