### ISSUE TITLE
Support drift detection

### ISSUE THREAD

**Issue by suzuki-shunsuke** [suzuki-shunsuke/tfaction#851]
## Overview

Support drift detection.
If Terraform Configuration is different from actual state of the infrastructure, tfaction notifies the drift to users and encourage users to fix the drift.

## Why this feature is needed?

To resolve the drift as soon as possible.

## How to implement

- Run `terraform plan` in each working directory periodically (weekly?)
  - [schedule](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule)
- If the result of `terraform plan` has changes, notifies it to codeowners
  - Create an issue and add it to GitHub Project
    - Terraform Drift Detection (working directory)
      - Add a link to latest pull request
  - Post a comment to Slack
- Store the state of cron jobs in Container Registries
  - https://oras.land/
  - https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry
- Open and close the issue
  - Open when terraform apply failed
  - Close when terraform apply succeeded

## Example Code

**Comment by suzuki-shunsuke** [comment]
# Idea 1.

- Update issue every time `terraform apply`, `tfmigrate apply`, and `drift detection workflow` are run
  - terraform apply: https://github.com/suzuki-shunsuke/tfaction-example/blob/925b4193c7e8b7a516af860ecca093c798bde0a3/.github/workflows/apply.yaml#L124-L127
  - tfmigrate apply: https://github.com/suzuki-shunsuke/tfaction-example/blob/925b4193c7e8b7a516af860ecca093c798bde0a3/.github/workflows/apply.yaml#L75-L78
  - Search an issue
  - Create or Close or Reopen an issue
  - Post a comment
- Get a least recently updated issue by GraphQL API
  - `sort:updated-asc`
  - https://docs.github.com/en/search-github/searching-on-github/searching-issues-and-pull-requests

**Comment by suzuki-shunsuke** [comment]
# actions

- apply
  - ⭐ update-drift-issue-after-apply
    - find an issue
    - ⭐ update-drift-issue
- schedule
  - ⭐ detect-drift
    - find an issue
    - ⭐ setup-base
    - plan
    - ⭐ update-drift-issue

**Comment by suzuki-shunsuke** [comment]
# Configuration

- tfaction-root.yaml
- .github/workflows/apply.yaml
- .github/workflows/schedule-create-drift-issues.yaml
- .github/workflows/schedule-detect-drifts.yaml

## tfaction-root.yaml

```yaml
drift_detection:
  enabled: true
  number_of_issues: 1
  duration: 168 # 24 * 7 = 7 days
```

## .github/workflows/apply.yaml

- Create an issue if the issue doesn't exist
- Create an issue commit to notify the result of `terraform apply` or `tfmigrate apply`
- Open or close the issue

```yaml
      - uses: suzuki-shunsuke/tfaction/update-drift-issue-after-apply@main
        if: always()
        with:
          github_app_token: ${{ steps.generate_token.outputs.token }}
```

## .github/workflows/schedule-create-drift-issues.yaml

- Run `tfaction create-drift-issues`

```yaml
name: Create drift issues
on:
  workflow_dispatch:
    inputs: {}
  schedule:
    # daily
    - cron: '0 0 * * *'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.0
      - uses: aquaproj/aqua-installer@v2.1.1
        with:
          aqua_version: v2.3.1
      - run: tfaction create-drift-issues
        env:
          GITHUB_TOKEN: ${{github.token}}
```

## .github/workflows/schedule-detect-drifts.yaml

- Get a least recently updated issue
- Run `terraform plan` and create an issue commit to notify the result of `terraform plan`
- Open or close the issue

```yaml
name: Detect drift
on:
  workflow_dispatch:
    inputs: {}
  schedule:
    # hourly
    - cron: '0 * * * *'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.0
      - uses: aquaproj/aqua-installer@v2.1.1
        with:
          aqua_version: v2.3.1
      - uses: suzuki-shunsuke/tfaction/detect-drift@main
        with:
          github_token: ${{github.token}}
```
