### ISSUE TITLE
An error is happening in tfmigrate-apply: The identifier 'global-config' may not be used more than once within the same scope.

### ISSUE THREAD

**Issue by yuya-takeyama** [suzuki-shunsuke/tfaction#906]
## Problem

We have a GitHub Actions Workflow using `tfmigrate-apply@v0.6.0-2`.

```yaml
      - uses: suzuki-shunsuke/tfaction/tfmigrate-apply@v0.6.0-2
        with:
          github_token: ${{ steps.generate_token.outputs.token }}
          github_app_token: ${{ steps.generate_token.outputs.token }}
```

But it fails in the startup of the Job.

```
Error: suzuki-shunsuke/tfaction/v0.6.0-2/tfmigrate-apply/action.yaml (Line: 21, Col: 11): The identifier 'global-config' may not be used more than once within the same scope.
```

<img width="1094" alt="image" src="https://user-images.githubusercontent.com/241542/235116599-9edd6f6f-f3cf-4bd8-a475-8cce598cca84.png">

The error is from here:
https://github.com/suzuki-shunsuke/tfaction/blob/v0.6.0-2/tfmigrate-apply/action.yaml#L20-L21

## Version

v0.6.0-2
